spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/TravelAgency2
    username: docker
    password: docker
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
  main:
    banner-mode: off